r"""
Database models.

    User  1---*  Paper  1---*  Section  1---*  Chunk
                   |                             ^
                   |---*  ChatMessage            |
                   |---*  AnalysisJob            |
                   \---*  Chunk  ----------------/

A Chunk row holds the text of a slice of the paper, the page it came from, and
**its embedding**, as a float32 blob in the `embedding` column. Vectors used to
live in ChromaDB, joined by chunk id; they do not any more. One paper is a few
hundred vectors, and searching it is one NumPy dot product over an array we load
on demand and drop again -- which does not justify keeping a vector database
resident in a 512MB process. See app/rag/vector_store.py.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Boolean,
    Index,
    Integer,
    LargeBinary,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def _uuid() -> str:
    return str(uuid.uuid4())


def _now() -> datetime:
    return datetime.now(timezone.utc)


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    email: Mapped[str] = mapped_column(String(320), unique=True, index=True)
    full_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    hashed_password: Mapped[str] = mapped_column(String(255))
    # Embedded in every refresh token; bump it to revoke all of them at once
    # (logout everywhere). See security.create_refresh_token.
    token_version: Mapped[int] = mapped_column(Integer, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now)

    papers: Mapped[list["Paper"]] = relationship(
        back_populates="owner", cascade="all, delete-orphan"
    )


class Paper(Base):
    __tablename__ = "papers"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    user_id: Mapped[str] = mapped_column(ForeignKey("users.id"), index=True)

    title: Mapped[str] = mapped_column(String(500))
    filename: Mapped[str] = mapped_column(String(500))
    file_path: Mapped[str] = mapped_column(String(1000))

    # SHA-256 of the uploaded bytes, computed while streaming it to disk.
    # Re-uploading the same file returns the existing paper instead of parsing
    # and embedding it again. Scoped per user, not globally: a global lookup
    # would hand one user a paper another user had already ingested, which is
    # both a privacy leak and a way to probe what others have uploaded.
    content_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # Set when the paper was fetched from a link (arXiv, DOI) rather than
    # uploaded. Also the signal that title/authors/abstract came from the
    # source's own metadata and must not be overwritten by the parser's guess.
    source_url: Mapped[str | None] = mapped_column(String(1000), nullable=True)

    # --- Bibliographic front matter, extracted at parse time ---
    authors: Mapped[str | None] = mapped_column(Text, nullable=True)
    venue: Mapped[str | None] = mapped_column(String(500), nullable=True)
    year: Mapped[str | None] = mapped_column(String(16), nullable=True)
    abstract: Mapped[str | None] = mapped_column(Text, nullable=True)

    num_pages: Mapped[int] = mapped_column(Integer, default=0)
    num_chunks: Mapped[int] = mapped_column(Integer, default=0)
    # True when the text came from model transcription of a scanned PDF rather
    # than from the file's own text layer. Shown in the UI: OCR can mis-read.
    ocr: Mapped[bool] = mapped_column(Boolean, default=False)

    # pending -> processing -> ready | failed
    status: Mapped[str] = mapped_column(String(20), default="pending", index=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    # --- Deep analysis (Phase 2) ---
    # The reduced, paper-level report as a JSON string, plus the version of the
    # prompt module that produced it. The version is what makes the cache
    # correct: editing a prompt changes the output, so a report generated by an
    # older prompt must not be served as if it were current.
    analysis_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    analysis_prompt_version: Mapped[str | None] = mapped_column(String(32), nullable=True)

    # Reference list enriched from OpenAlex, cached as JSON; see
    # services/related.py. Null until first requested.
    related_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    # --- Conversation memory (Phase 3) ---
    # Older turns rolled into a running summary, plus the highest turn_index it
    # covers. Recent turns are replayed verbatim; everything before this point
    # is represented by the summary, so a long chat cannot grow the prompt
    # without bound.
    chat_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    chat_summary_upto: Mapped[int] = mapped_column(Integer, default=-1)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now)

    owner: Mapped["User"] = relationship(back_populates="papers")
    sections: Mapped[list["Section"]] = relationship(
        back_populates="paper", cascade="all, delete-orphan"
    )
    chunks: Mapped[list["Chunk"]] = relationship(
        back_populates="paper", cascade="all, delete-orphan"
    )
    messages: Mapped[list["ChatMessage"]] = relationship(
        back_populates="paper", cascade="all, delete-orphan"
    )
    jobs: Mapped[list["AnalysisJob"]] = relationship(
        back_populates="paper", cascade="all, delete-orphan"
    )

    __table_args__ = (
        # The dedupe lookup is (user_id, content_hash); indexing both together
        # means it is one index seek rather than a scan of the user's papers.
        Index("ix_papers_user_hash", "user_id", "content_hash"),
    )


class Section(Base):
    """A logical section of the paper: Abstract, Methods, Results, ...

    Sections exist as rows rather than as a label on each chunk because the deep
    analysis maps over them: each one gets its own LLM call with a prompt chosen
    for its type, and the result is stored right here on the row. Recomputing
    only the sections whose analysis is missing is then trivial.
    """

    __tablename__ = "sections"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    paper_id: Mapped[str] = mapped_column(ForeignKey("papers.id"), index=True)

    # Display name as it appeared in the paper, e.g. "3.2 Training Details".
    name: Mapped[str] = mapped_column(String(300))
    # Normalised type used to pick a prompt: abstract | introduction |
    # related_work | method | experiments | results | discussion | limitations |
    # conclusion | references | other.
    kind: Mapped[str] = mapped_column(String(40), default="other", index=True)

    ordinal: Mapped[int] = mapped_column(Integer)  # order within the paper
    page_start: Mapped[int] = mapped_column(Integer)
    page_end: Mapped[int] = mapped_column(Integer)
    char_count: Mapped[int] = mapped_column(Integer, default=0)

    # Output of the map stage for this section: a JSON string. Null until the
    # analysis job has processed it.
    analysis_json: Mapped[str | None] = mapped_column(Text, nullable=True)

    paper: Mapped["Paper"] = relationship(back_populates="sections")
    # back_populates targets `section_ref`, not `section`: Chunk.section is a
    # denormalised String column holding the section's name, and the ORM would
    # otherwise try to treat that column as the reverse relationship.
    chunks: Mapped[list["Chunk"]] = relationship(back_populates="section_ref")


class Chunk(Base):
    __tablename__ = "chunks"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    paper_id: Mapped[str] = mapped_column(ForeignKey("papers.id"), index=True)
    section_id: Mapped[str | None] = mapped_column(
        ForeignKey("sections.id"), nullable=True, index=True
    )

    content: Mapped[str] = mapped_column(Text)
    # Chunks follow section boundaries, so one can span a page break. Both ends
    # are recorded and a citation renders "page 4" or "pages 4-6" accordingly.
    # The previous design forbade crossing pages to guarantee a single page per
    # chunk; that made citations simpler and passages worse. See chunker.py.
    page_start: Mapped[int] = mapped_column(Integer)
    page_end: Mapped[int] = mapped_column(Integer)
    chunk_index: Mapped[int] = mapped_column(Integer)  # order within the paper

    # Denormalised copy of Section.name. Retrieval renders a citation label for
    # every hit, and joining to sections for each of 8-12 hits per query to read
    # one string is not worth it. The section rows are written once and never
    # renamed, so the copy cannot drift.
    section: Mapped[str | None] = mapped_column(String(300), nullable=True)

    # float32 little-endian, EMBEDDING_DIM values, via numpy .tobytes().
    # float32 not float64: these are unit vectors whose components are ~1e-2,
    # and float32 has ~7 significant digits -- far more than cosine ranking
    # needs. It also halves the row size and the array we build at query time.
    # Null if embedding failed; retrieval skips those rather than crashing.
    embedding: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)

    paper: Mapped["Paper"] = relationship(back_populates="chunks")
    section_ref: Mapped["Section"] = relationship(back_populates="chunks")

    __table_args__ = (
        # Every retrieval path reads one paper's chunks in order.
        Index("ix_chunks_paper_order", "paper_id", "chunk_index"),
    )


class AnalysisJob(Base):
    """Progress record for a background deep-analysis run.

    This table is the entire contract between the background task and the UI.
    The frontend polls it, so it has to carry enough to render a real progress
    bar rather than a spinner: which stage, how far through it, and what the
    stage is called in words.
    """

    __tablename__ = "analysis_jobs"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    paper_id: Mapped[str] = mapped_column(ForeignKey("papers.id"), index=True)

    # queued | running | done | failed
    status: Mapped[str] = mapped_column(String(20), default="queued", index=True)
    # parsing | embedding | analyzing | synthesizing | done
    stage: Mapped[str] = mapped_column(String(32), default="queued")
    # Position within the current stage, e.g. section 3 of 9. Both zero when the
    # stage has no meaningful subdivision.
    current: Mapped[int] = mapped_column(Integer, default=0)
    total: Mapped[int] = mapped_column(Integer, default=0)
    message: Mapped[str] = mapped_column(String(300), default="")

    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    prompt_version: Mapped[str | None] = mapped_column(String(32), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=_now, onupdate=_now)

    paper: Mapped["Paper"] = relationship(back_populates="jobs")


class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    paper_id: Mapped[str] = mapped_column(ForeignKey("papers.id"), index=True)

    role: Mapped[str] = mapped_column(String(20))  # "user" | "assistant"
    content: Mapped[str] = mapped_column(Text)
    # Position in the conversation, same idea as Chunk.chunk_index. Ordering by
    # created_at alone is wrong: a question and its answer are written in the
    # same transaction and routinely share a timestamp (the Windows clock ticks
    # about every 15ms), and the id is a random UUID, so the tie-break is random
    # too -- history comes back with the answer above the question. Order is
    # data, so we store it rather than infer it.
    turn_index: Mapped[int] = mapped_column(Integer, default=0)
    # For assistant turns: JSON list of {chunk_id, page_number, section, snippet}
    citations_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now)

    paper: Mapped["Paper"] = relationship(back_populates="messages")


class LLMCall(Base):
    """One row per language-model or embedding request.

    This table is the whole observability story, and it is enough: "what did
    this paper cost?" and "how many calls failed today?" are both one query.
    The unconstrained answer is OpenTelemetry and a tracing backend; on a free
    tier there is nowhere to send traces and the exporter is another resident
    client. A table in the database we already have costs nothing.

    `paper_id` is not a foreign key on purpose. Deleting a paper should not
    erase the record that it cost 40 calls -- usage totals must survive the
    thing they measured.
    """

    __tablename__ = "llm_calls"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    paper_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    # ingest | map | reduce | chat | expand | summary | followups | judge | other
    purpose: Mapped[str] = mapped_column(String(32), default="other", index=True)
    # generate | stream | embed
    kind: Mapped[str] = mapped_column(String(16), default="generate")
    model: Mapped[str] = mapped_column(String(100))
    # Null when the provider did not report them (embedding calls report the
    # number of texts here instead, so batching is still visible).
    prompt_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    latency_ms: Mapped[int] = mapped_column(Integer, default=0)
    ok: Mapped[bool] = mapped_column(Boolean, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_now, index=True)
